branches:
- main
- name: beta
  prerelease: true
  channel: beta

plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/changelog"
- "@semantic-release/npm"
- "@semantic-release/github"
- - "@semantic-release/git"
  - assets:
    - package.json
    - CHANGELOG.md
    message: "chore(release): ${nextRelease.version} [skip ci]


      ${nextRelease.notes}"

# Additional configuration
tagFormat: "v${version}"
preset: "angular"

# Release notes configuration
releaseNotes:
  preset: "angular"
  parserOpts:
    noteKeywords:
    - BREAKING CHANGE
    - BREAKING CHANGES
  writerOpts:
    groupBy: "type"
    commitGroupsSort: "title"
    commitsSort: "header"

# Changelog configuration
changelogFile: "CHANGELOG.md"
changelogTitle: "# Changelog


  All notable changes to this project will be documented in this file. See [standard-version](https://github.com/conventional-changelog/standard-version) for commit guidelines."
